version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - ./homeassistant/config:/config
      - ./homeassistant/resolv.conf:/etc/resolv.conf:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
    volumes:
      - ./pihole/etc-pihole/:/etc/pihole/
      - ./pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
      - ./pihole/resolv.conf:/etc/resolv.conf:ro
    ports:
      # DNS pihole-FTL
      - '53:53/tcp'
      - '53:53/udp'
      # DHCP pihole-FTL
      - '67:67/tcp'
      - '67:67/udp'
      # HTTP lighttpd
      - '80:80/tcp'
    cap_add:
      - NET_ADMIN

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: unless-stopped
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '9000:9000'
